version: "3"
services:
  db:
    image: mysql:5.7
    networks:
      - web-db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=dostavim
    ports:
      - 33306:3306
    restart: always
    healthcheck:
      interval: 5s
      timeout: 1s
      retries: 30
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-padmin",
        ]
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./scripts/CREATE.sql:/docker-entrypoint-initdb.d/initdb.sql

  web-app:
    build: ./DostavimVse
    ports:
      - 18080:8080
    networks:
      - web-db
    depends_on:
      db:
        condition: service_healthy
    restart: always

networks:
  web-db:
